/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Syriac_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[6] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 6; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xdc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xdd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xe0)) { goto error; }
	for (i = 0x80; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[4], i)) { goto error; }
	}
	for (i = 0x8f; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[4], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0xa1)) { goto error; }
	for (i = 0xa0; i <= 0xaa; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[4], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[4], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

