/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Co_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[10] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 10; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xee)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xf3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xf4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[6], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[7], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[9], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[8], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[8], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[8], 0xbd)) { goto error; }

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[8], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

