/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Sm_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[41] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 41; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], '+')) { goto error; }
	for (i = 0x3c; i <= 0x3e; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[1], '|')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[1], '~')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xc3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xcf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xd8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xe2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xb6)) { goto error; }
	for (i = 0x86; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[9], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[10], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[11], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[12], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[13], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[14], 0x87)) { goto error; }
	for (i = 0x88; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[15], i)) { goto error; }
	}
	for (i = 0xa4; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[15], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[15], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[16], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[17], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[18], 0x8e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[19], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[20], 0x96)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[21], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[22], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[23], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[24], 0xa6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[25], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[26], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[27], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[28], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[29], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[30], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[31], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[32], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[33], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[34], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x92)) { goto error; }
	for (i = 0xba; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[9], s[1], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[11], s[1], 0x98)) { goto error; }
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[12], s[1], 0x8b)) { goto error; }
	for (i = 0x90; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xae)) { goto error; }
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[14], s[1], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[1], 0x94)) { goto error; }
	for (i = 0xb4; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[16], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xbc)) { goto error; }
	for (i = 0x9b; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[1], i)) { goto error; }
	}
	for (i = 0x9c; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[20], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[1], 0x81)) { goto error; }
	for (i = 0xb8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[22], s[1], 0xaf)) { goto error; }
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0x87; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0x99; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { goto error; }
	}
	for (i = 0x9c; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { goto error; }
	}
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[1], i)) { goto error; }
	}
	for (i = 0x87; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[29], s[1], 0xa2)) { goto error; }
	for (i = 0xa4; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[30], s[1], 0x8b)) { goto error; }
	for (i = 0x9c; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[30], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa2)) { goto error; }
	for (i = 0xa9; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[33], s[35], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[36], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[37], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[38], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[39], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[34], s[40], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x83)) { goto error; }
	for (i = 0xb0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[1], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[1], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

