/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_all_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[7] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 7; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[0], i)) { goto error; }
	}
	for (i = 0x7f; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xf4)) { goto error; }
	if (!fsm_addedge_any(fsm, s[1], s[1])) { goto error; }
	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[0], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[0], '\x7f')) { goto error; }
	for (i = 0xc0; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[6], 0xf4)) { goto error; }
	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0x7f; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0xc0; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[2], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[6], 0xf4)) { goto error; }
	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[0], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[0], '\x7f')) { goto error; }
	for (i = 0xa0; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[2], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[6], 0xf4)) { goto error; }
	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0x7f; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0xc0; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[5], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[2], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[5], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[6], 0xf4)) { goto error; }
	for (i = 0x00; i <= 0x08; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[0], i)) { goto error; }
	}
	for (i = 0x0b; i <= 0x0c; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[0], i)) { goto error; }
	}
	for (i = 0x0e; i <= 0x1f; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[0], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[0], '\x7f')) { goto error; }
	for (i = 0x90; i <= 0xc1; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[0], i)) { goto error; }
	}
	for (i = 0xf5; i <= 0xff; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[0], i)) { goto error; }
	}
	for (i = 0x09; i <= 0x0a; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], '\r')) { goto error; }
	for (i = 0x20; i <= 0x7e; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[2], i)) { goto error; }
	}
	for (i = 0xc2; i <= 0xdf; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[2], i)) { goto error; }
	}
	for (i = 0xe1; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[2], i)) { goto error; }
	}
	for (i = 0xee; i <= 0xef; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[2], i)) { goto error; }
	}
	for (i = 0xf1; i <= 0xf3; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[2], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[3], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[4], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[5], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[6], 0xf4)) { goto error; }

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[1], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

