/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Mongolian_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[9] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 9; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[3], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[4], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[5], 0xa2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[7], 0x91)) { goto error; }
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[6], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[6], 0x84)) { goto error; }
	for (i = 0x86; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[6], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[6], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[6], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[6], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xaa; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[6], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[8], 0x99)) { goto error; }
	for (i = 0xa0; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[6], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[6], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

