/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Sk_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[24] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 24; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], '^')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[1], '`')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xcb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xcd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xce)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xe3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xea)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[9], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[10], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xa8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xb8)) { goto error; }
	for (i = 0x82; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	for (i = 0x92; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	for (i = 0xa5; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0xad)) { goto error; }
	for (i = 0xaf; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xb5)) { goto error; }
	for (i = 0x84; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[22], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[23], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[11], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[19], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[20], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[21], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[14], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[15], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[16], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[17], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[18], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[10], s[12], 0x9f)) { goto error; }
	for (i = 0x9b; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[12], s[13], 0x8f)) { goto error; }
	for (i = 0xbb; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	for (i = 0xb2; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa3)) { goto error; }
	for (i = 0x80; i <= 0x96; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[1], i)) { goto error; }
	}
	for (i = 0x89; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[21], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[1], 0xbf)) { goto error; }
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0x9d; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0xad; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0xbd; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[1], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

