/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Pf_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[6] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 6; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xe2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[5], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[3], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[4], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[5], 0xba)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x8a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[5], 0xa1)) { goto error; }

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[5], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

