/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Common_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[107] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 107; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	for (i = 0x00; i <= 0x40; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	for (i = 0x5b; i <= 0x60; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	for (i = 0x7b; i <= 0x7f; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xc3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xca)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xcb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xcd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xce)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xd6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[9], 0xd8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[10], 0xd9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[11], 0xdb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[12], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[13], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[14], 0xe2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[15], 0xe3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[16], 0xe4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[17], 0xea)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[18], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[19], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[20], 0xf3)) { goto error; }
	for (i = 0x80; i <= 0xa9; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	for (i = 0xab; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[1], 0xb7)) { goto error; }
	for (i = 0xb9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	for (i = 0xa5; i <= 0xa9; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	for (i = 0xac; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[10], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[11], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[71], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[76], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[77], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[78], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[39], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[40], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[41], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[42], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[43], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[21], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[22], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[23], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[24], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[25], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[26], 0x86)) { goto error; }
	for (i = 0x87; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[27], i)) { goto error; }
	}
	for (i = 0x92; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[27], i)) { goto error; }
	}
	for (i = 0xa4; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[27], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[14], s[27], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[28], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[29], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[30], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[31], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[32], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[33], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[34], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[27], 0x8a)) { goto error; }
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[27], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[15], s[79], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[80], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[81], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[82], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[83], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[84], 0x88)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[85], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[86], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[87], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[27], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[62], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[63], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[64], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[65], 0xa4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[66], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[67], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[68], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[69], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[70], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[71], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[72], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[73], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[74], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[75], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[19], s[35], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[19], s[36], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[19], s[37], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[19], s[38], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[20], s[45], 0xa0)) { goto error; }
	for (i = 0x80; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { goto error; }
	}
	for (i = 0x8e; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[1], i)) { goto error; }
	}
	for (i = 0xa6; i <= 0xb0; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[1], i)) { goto error; }
	}
	for (i = 0xb4; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0xa7; i <= 0xa9; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0xac; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0xb3; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { goto error; }
	}
	for (i = 0x8f; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { goto error; }
	}
	for (i = 0x89; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[30], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[30], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x95; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	for (i = 0x98; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[1], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x92; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[1], i)) { goto error; }
	}
	for (i = 0xac; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[33], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[35], s[46], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[47], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[48], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[49], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[44], 0xb2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[21], 0x9f)) { goto error; }
	for (i = 0x80; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[27], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[37], s[27], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[27], 0x90)) { goto error; }
	for (i = 0x96; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[27], i)) { goto error; }
	}
	for (i = 0x9b; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[27], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[37], s[50], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[51], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[52], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[53], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[54], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[55], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[56], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[57], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[58], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[59], 0x94)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[60], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[61], 0x9a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[27], 0x81)) { goto error; }
	for (i = 0x8c; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[38], s[27], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[38], s[27], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[27], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[89], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[89], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[90], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[91], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[92], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[93], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[94], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[95], 0x88)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[96], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[97], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[98], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[99], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[100], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[101], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[102], 0xa2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[103], 0xa4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[104], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[105], 0xa6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[106], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xbb)) { goto error; }
	for (i = 0xab; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[1], i)) { goto error; }
	}
	for (i = 0xb5; i <= 0xb6; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[1], i)) { goto error; }
	}
	for (i = 0x82; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[42], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[43], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[43], s[1], 0xa1)) { goto error; }
	for (i = 0xa9; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[1], i)) { goto error; }
	}
	for (i = 0xae; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[1], i)) { goto error; }
	}
	for (i = 0xb5; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[45], s[27], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[45], s[88], 0x80)) { goto error; }
	for (i = 0x80; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[1], i)) { goto error; }
	}
	for (i = 0x87; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[1], i)) { goto error; }
	}
	for (i = 0xb7; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[47], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[1], i)) { goto error; }
	}
	for (i = 0xa1; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0xa9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0xaa; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0x83; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[1], i)) { goto error; }
	}
	for (i = 0x8c; i <= 0xa9; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[1], i)) { goto error; }
	}
	for (i = 0xae; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa8; i++) {
		if (!fsm_addedge_literal(fsm, s[54], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x96; i++) {
		if (!fsm_addedge_literal(fsm, s[55], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[55], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[57], s[1], 0xa2)) { goto error; }
	for (i = 0xa5; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	for (i = 0xa9; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	for (i = 0xae; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[57], s[1], 0xbb)) { goto error; }
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[1], i)) { goto error; }
	}
	for (i = 0x85; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x87; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[60], s[1], 0x86)) { goto error; }
	for (i = 0x8a; i <= 0x90; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[1], i)) { goto error; }
	}
	for (i = 0x92; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[1], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[1], i)) { goto error; }
	}
	for (i = 0x88; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[65], s[1], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[67], s[1], 0x9b)) { goto error; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[68], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[69], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[69], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x92; i++) {
		if (!fsm_addedge_literal(fsm, s[70], s[1], i)) { goto error; }
	}
	for (i = 0x94; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[70], s[1], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[70], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[71], s[1], 0xbf)) { goto error; }
	for (i = 0x81; i <= 0xa0; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[1], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[73], s[1], 0x80)) { goto error; }
	for (i = 0x9b; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[73], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[73], s[1], 0xb0)) { goto error; }
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[74], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	for (i = 0xb9; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[76], s[1], 0xa2)) { goto error; }
	for (i = 0xa4; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[77], s[1], i)) { goto error; }
	}
	for (i = 0x95; i <= 0x98; i++) {
		if (!fsm_addedge_literal(fsm, s[78], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[79], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[79], s[1], 0x86)) { goto error; }
	for (i = 0x88; i <= 0xa0; i++) {
		if (!fsm_addedge_literal(fsm, s[79], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[79], s[1], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[79], s[1], i)) { goto error; }
	}
	for (i = 0x9b; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[80], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[80], s[1], 0xa0)) { goto error; }
	for (i = 0xbb; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[81], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[82], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[83], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[84], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[85], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[85], s[1], 0xbf)) { goto error; }
	for (i = 0x80; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[86], s[1], i)) { goto error; }
	}
	for (i = 0x98; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[87], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[88], s[1], 0x81)) { goto error; }
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[88], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[89], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[89], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[90], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[90], s[1], i)) { goto error; }
	}
	for (i = 0xb1; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[90], s[1], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[91], s[1], i)) { goto error; }
	}
	for (i = 0x91; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[91], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[92], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[92], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[92], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[93], s[1], i)) { goto error; }
	}
	for (i = 0xa6; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[94], s[1], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[95], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[95], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[96], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x91; i++) {
		if (!fsm_addedge_literal(fsm, s[96], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[96], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[97], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[97], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[97], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[98], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[99], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[100], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[100], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[101], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[101], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[101], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[102], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[102], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[104], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[104], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[105], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[106], s[1], 0x80)) { goto error; }
	for (i = 0x90; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[106], s[1], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[1], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

