/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Ll_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[80] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 80; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}

	for (i = 0x61; i <= 0x7a; i++) { /* 'a' .. 'z' */
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xc3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xc4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xc5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xc6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xc7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xc8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[9], 0xc9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[10], 0xca)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[11], 0xcd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[12], 0xce)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[13], 0xcf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[14], 0xd0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[15], 0xd1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[16], 0xd2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[17], 0xd3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[18], 0xd4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[19], 0xd5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[20], 0xd6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[21], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[22], 0xe2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[23], 0xea)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[24], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[25], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xb5)) { goto error; }
	for (i = 0x9f; i <= 0xb6; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	for (i = 0xb8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xb5)) { goto error; }
	for (i = 0xb7; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xba)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[4], s[1], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x86)) { goto error; }
	for (i = 0x88; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xba)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[1], 0xbc)) { goto error; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x88)) { goto error; }
	for (i = 0x8c; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x95)) { goto error; }
	for (i = 0x99; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xa8)) { goto error; }
	for (i = 0xaa; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0xb6)) { goto error; }
	for (i = 0xb9; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x8e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x94)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x96)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x98)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x9a)) { goto error; }
	for (i = 0x9c; i <= 0x9d; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xad)) { goto error; }
	for (i = 0xaf; i <= 0xb0; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[7], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xb1)) { goto error; }
	for (i = 0xb3; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[8], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[9], s[1], 0x8d)) { goto error; }
	for (i = 0x8f; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[9], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[1], i)) { goto error; }
	}
	for (i = 0x95; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[11], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[11], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[11], s[1], 0xb7)) { goto error; }
	for (i = 0xbb; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[12], s[1], 0x90)) { goto error; }
	for (i = 0xac; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x91; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	for (i = 0x95; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xad)) { goto error; }
	for (i = 0xaf; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[1], 0xb8)) { goto error; }
	for (i = 0xbb; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x88)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x8a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x8c)) { goto error; }
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[1], 0xaf)) { goto error; }
	for (i = 0xa1; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[1], i)) { goto error; }
	}
	for (i = 0xb8; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[32], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[21], s[32], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[43], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[44], 0xb2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[45], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[46], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[47], 0xb6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[48], 0xba)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[49], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[50], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[51], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[52], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[14], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[28], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[29], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[30], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[31], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[32], 0xb2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[33], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[34], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[14], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[35], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[36], 0x9a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[37], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[38], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[39], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[40], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[41], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[23], s[42], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[24], s[26], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[24], s[27], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[25], s[53], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[25], s[54], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[25], s[55], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[25], s[56], 0x9e)) { goto error; }
	for (i = 0x80; i <= 0x86; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { goto error; }
	}
	for (i = 0x93; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0x8a)) { goto error; }
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[28], s[1], 0xb9)) { goto error; }
	for (i = 0xbc; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[1], i)) { goto error; }
	}
	for (i = 0x86; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[29], s[1], 0x8e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[30], s[1], 0x84)) { goto error; }
	for (i = 0x80; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0xa1)) { goto error; }
	for (i = 0xa5; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0xa8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0xaa)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[31], s[1], 0xb1)) { goto error; }
	for (i = 0xb3; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[32], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0xa1)) { goto error; }
	for (i = 0xa3; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[33], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[33], s[1], 0xb3)) { goto error; }
	for (i = 0x80; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[34], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[34], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[35], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[36], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xad)) { goto error; }
	for (i = 0xaf; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[37], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xaf)) { goto error; }
	for (i = 0xb1; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[38], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xba)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[1], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x8e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x91)) { goto error; }
	for (i = 0x93; i <= 0x95; i++) {
		if (!fsm_addedge_literal(fsm, s[39], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[40], s[1], 0xba)) { goto error; }
	for (i = 0x80; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[1], i)) { goto error; }
	}
	for (i = 0xb8; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[45], s[1], i)) { goto error; }
	}
	for (i = 0xab; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[1], i)) { goto error; }
	}
	for (i = 0xb9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[47], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x8b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x93)) { goto error; }
	for (i = 0x95; i <= 0x9d; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[48], s[1], 0xbf)) { goto error; }
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x95; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[51], s[1], 0xbe)) { goto error; }
	for (i = 0x82; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0x86; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0xb2; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[53], s[57], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[53], s[58], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[53], s[59], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[53], s[60], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[54], s[77], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[61], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[62], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[63], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[64], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[65], 0x94)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[66], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[67], 0x96)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[68], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[69], 0x98)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[70], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[71], 0x9a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[72], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[73], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[74], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[75], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[55], s[76], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[56], s[78], 0xa4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[56], s[79], 0xa5)) { goto error; }
	for (i = 0xa8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[1], i)) { goto error; }
	}
	for (i = 0x98; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[1], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[1], i)) { goto error; }
	}
	for (i = 0x8e; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[1], i)) { goto error; }
	}
	for (i = 0x82; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[63], s[1], 0xbb)) { goto error; }
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[1], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[1], i)) { goto error; }
	}
	for (i = 0xaa; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[65], s[1], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[65], s[1], i)) { goto error; }
	}
	for (i = 0x92; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[66], s[1], i)) { goto error; }
	}
	for (i = 0x86; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[67], s[1], i)) { goto error; }
	}
	for (i = 0xba; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[67], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[68], s[1], i)) { goto error; }
	}
	for (i = 0xae; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[68], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[69], s[1], i)) { goto error; }
	}
	for (i = 0xa2; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[69], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[70], s[1], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[71], s[1], i)) { goto error; }
	}
	for (i = 0x82; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[1], i)) { goto error; }
	}
	for (i = 0x9c; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[1], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[73], s[1], i)) { goto error; }
	}
	for (i = 0x96; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[73], s[1], i)) { goto error; }
	}
	for (i = 0xb6; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[73], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[74], s[1], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x95; i++) {
		if (!fsm_addedge_literal(fsm, s[74], s[1], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[74], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	for (i = 0xaa; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[76], s[1], i)) { goto error; }
	}
	for (i = 0x84; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[76], s[1], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[76], s[1], 0x8b)) { goto error; }
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[77], s[1], i)) { goto error; }
	}
	for (i = 0xa2; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[78], s[1], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[79], s[1], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[1], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

