/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Cs_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	fsm_state_t s[1] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 1; i++) {
		if (!fsm_addstate(fsm, &s[i])) {
			goto error;
		}
	}


	fsm_setstart(fsm, s[0]);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

